---
name: "Flake Lock Update Action"
run-name: "nfu"
on: 
  workflow_dispatch: 
  schedule: 
    - cron: '0 0 * * 0'

jobs:
  locker:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4
      - name: nix install
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: flake check
        uses: DeterminateSystems/flake-checker-action@v5
      - name: flake update
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "Update flake.lock Action"
          pr-labels: |
            CI/CD
            automated
          git-author-name: John Nix
          git-author-email: github-actions[bot]@users.noreply.github.com
          git-committer-name: John Nix
          git-committer-email: github-actions[bot]@users.noreply.github.com
          pr-assignees: s0me1newithhand7s
          pr-reviewers: s0me1newithhand7s